- Add a web UI:
    id: djdxboyt
- Add querying capabilities:
    id: yvyqqnhp
- ? 'Add commit-msg help: https://stackoverflow.com/questions/3966714/how-can-i-change-the-default-comments-in-the-git-commit-message'
  : id: tzwvlfqg
