- Add a web UI:
    id: djdxboyt
- Add querying capabilities:
    id: yvyqqnhp
- ? 'Add commit-msg help: https://stackoverflow.com/questions/3966714/how-can-i-change-the-default-comments-in-the-git-commit-message'
  : id: tzwvlfqg
- 'Change id-s into tags and add terminal coloring: https://pypi.org/project/colorama/':
    id: fioavvfp
- Evaluate compatibility options with https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus:
    id: mfngougx
- Migrate to argparse + argcomplete:
    id: vyzzvxsc
- 'Allow reordering of tasks - https://stackoverflow.com/questions/3173154/move-an-item-inside-a-list ':
    id: ibmemvra
- Evaluate https://github.com/MichaelMure/git-bug and https://github.com/dspinellis/git-issue:
    id: hvugeuhu
