language: bash
dist: trusty
services: docker
addons:
  sonarcloud:
    organization: bessbd-github
script:
- make test
- sonar-scanner
deploy:
  provider: script
  script: make release
  on:
    tags: true
