language: bash
services: docker
python:
- 3.7-dev
script: bash test.sh
deploy:
  provider: script
  script: pip3 install setuptools twine && python3 setup.py sdist bdist_wheel && twine upload dist/*
  on:
    tags: true
