language: bash
services: docker
script: bash test.sh
deploy:
  provider: script
  script: docker run --mount src="$(pwd)",target=/app,type=bind -it python bash -c "cd /app && pip3 install twine && python3 setup.py sdist bdist_wheel && twine upload dist/*"
  on:
    tags: true
